Repository libsv/go-dpp, pull requests merged in 2021-09, with the labels that each got.

#4 Fix: Docker build config & Destinations API
  Dockerfile
  Makefile
  cmd/rest-server/main.go
  data/noop/noop.go
  data/payd/models/payd.go
  data/payd/payd.go
  destinations.go
  docker-compose.build.yml
  docker-compose.yml
  mocks/destination_reader.go
  mocks/fee_reader.go
  mocks/mocks.go
  payment_request.go
  service/paymentrequest.go
Labels: bug

#10 Fix: P4 Naming, and docker compose
  README.md
  cmd/rest-server/main.go
  config/defaults.go
  data/noop/noop.go
  data/payd/models/payd.go
  data/payd/payd.go
  destinations.go
  docker-compose.yml
  docs/docs.go
  go.mod
  merchant.go
  mocks/destination_reader.go
  mocks/merchant_reader.go
  mocks/payment_writer.go
  payment.go
  payment_request.go
  payment_test.go
  pptcl.go
  service/payment.go
  service/paymentrequest.go
  transports/http/middleware/error_handler.go
  transports/http/payment.go
  transports/http/payment_request.go
Labels: bug

#11 Updating golint to revive
  .github/mergify.yml
  .github/workflows/go.yml
  .golangci.yml
  data/http_client.go
  data/payd/payd.go
Labels: bug

#13 Feat/optional spv
  data/http_client.go
  data/payd/models/payd.go
  data/payd/payd.go
  destinations.go
  go.mod
  go.sum
  payment.go
  payment_request.go
  payment_test.go
  service/paymentrequest.go
  vendor/gopkg.in/guregu/null.v3/.gitignore
  vendor/gopkg.in/guregu/null.v3/LICENSE
  vendor/gopkg.in/guregu/null.v3/README.md
  vendor/gopkg.in/guregu/null.v3/bool.go
  vendor/gopkg.in/guregu/null.v3/float.go
  vendor/gopkg.in/guregu/null.v3/int.go
  vendor/gopkg.in/guregu/null.v3/string.go
  vendor/gopkg.in/guregu/null.v3/time.go
  vendor/modules.txt
Labels: feature

#16 Feat/docker build
  .github/workflows/go.yml
  .goreleaser.yml
  Dockerfile.releaser
Labels: feature

#17 Fix/drop v prefix
  .goreleaser.yml
Labels: bug

#18 Debug Logger
  cmd/rest-server/main.go
  transports/http/middleware/debug_logger.go
Labels: enhancement

#20 Fix: Better error handling from payd
  data/http_client.go
  p4.go
Labels: bug
